name: Deployement CI/CD
on:
  push:
    branches: [ "master","main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Installation de PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2.12'

    - name: Téléchargement des fichiers
      uses: actions/checkout@v4
   
    - name: Installation des Dependences
      run: composer install 

  Create-Folder:
    name: Create-Folder
    runs-on: ubuntu-latest

    steps:
      - name: Create folder on remote VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p /public_html/MODEL_API_LARAVEL

  production:
    name: Deploiement en production
    runs-on: ubuntu-latest
    needs: Create-Folder

    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SECRET_KEY }}
        port: ${{ secrets.PORT }}
        source: "MODEL_API_LARAVEL"
        target: /public_html/MODEL_API_LARAVEL